services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_employees
    environment:
      MYSQL_ROOT_PASSWORD: employees
      MYSQL_DATABASE: employees
      MYSQL_USER: employees
      MYSQL_PASSWORD: employees
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
